### ISSUE TITLE
Game Crashes in the Park at Melody's minigame

### ISSUE THREAD

**Issue by Batlh** [KdGaming0/SkyBlock-Enhanced-Modpack#1]
The game crashes immediately the moment you talk to Melody and click anything in her selection screen to get the minigame started.
i added here the 3 crash logs that shows what is causing it.
[crash-2024-05-24_09.08.11-client.txt](https://github.com/KdGaming0/SkyBlock-Enhanced-Modpack/files/15430070/crash-2024-05-24_09.08.11-client.txt)
[crash-2024-05-24_09.11.10-client.txt](https://github.com/KdGaming0/SkyBlock-Enhanced-Modpack/files/15430071/crash-2024-05-24_09.11.10-client.txt)
[crash-2024-05-24_09.55.24-client.txt](https://github.com/KdGaming0/SkyBlock-Enhanced-Modpack/files/15430073/crash-2024-05-24_09.55.24-client.txt)

**Comment by KdGaming0** [comment]
Hello, thanks for reporting the crash and I hope you like my modpack. The crash is caused by Skyblock addons and Skyhanni. Skyhanni has a feature that enlarges the GUI in Melody to make it easier to play the harp. However, this causes the game to crash when Skyblock Addons is installed. I have submitted a bug report to Skyhanni so they can fix it. In the meantime, you can turn off the Melody harp GUI setting. You can find it by typing /sh and searching for Melody. It will be under helpers in the sidebar.

**Comment by Batlh** [comment]
thx :D and yes the modpack is good :3 but one little thing you should rly disable in the settings you ship the modpack with is the fullscreen mode.... the old 1.8.9 version tends to crash in this mode quite often :3  and people can decide then in the start screen for themselves if they want this fullscreen or not. ^^

**Comment by KdGaming0** [comment]
Thanks for the feedback. I will do that.
