### ISSUE TITLE
Can't launch Skyblock Enhanced on LabyMod

### ISSUE THREAD

**Issue by Yinkie66** [KdGaming0/SkyBlock-Enhanced-Modpack#3]
https://paste.labymod.net/koboqupefiqujasoqiko 

Dunno why this happens. I tried installing optifine with it and it didn't work.

PC:
AMD Ryzen 5 5600X
GeForce 1060 6GB

**Comment by KdGaming0** [comment]
I don't know why, I have heard that LabyMod breaks with other mods like Skytils and other skyblock mods. I recommend not using LabyMod because of this. If there is a specific Feature that you want or need i can maybe find a replacement mod for it. 

Also, did it work before you added optifine, it may be that you need to add optifine from the in-game add-on place for Labymod, I don't remember exactly how that worked it is a long time since I last used it.

**Comment by Yinkie66** [comment]
No it didn't work before I added optifine either. I will try installing the mods manually, but thank you!

**Comment by KdGaming0** [comment]
Can you tell me if it works if you do it manually so i can know if it is the modpack or a mod that doesn't work? Thanks.
